import { MathJax, MathJaxContext } from "better-react-mathjax";

const HypocycloidInfo = () => {
  return (
    <>
      <h2>Hypocycloid</h2>
      <p>
        A hypocycloid is a plane curve generated by tracing a point on the
        circumference of a circle—called the hypocycle—as it rolls without
        slipping along the inside of a fixed circle. It is a specific type of
        roulette.
      </p>
      <p>The parametric equations for a hypocycloid are:</p>
      <p>
        <MathJaxContext>
          <MathJax>
            {
              "\\(x = (R - r) \\cdot cos(\\theta) + r \\cdot cos((\\frac{R - r}{r}) \\cdot \\theta)\\)"
            }
          </MathJax>
        </MathJaxContext>
      </p>
      <p>
        <MathJaxContext>
          <MathJax>
            {
              "\\(y = (R - r) \\cdot sin(\\theta) - r \\cdot sin((\\frac{R - r}{r}) \\cdot \\theta)\\)"
            }
          </MathJax>
        </MathJaxContext>
      </p>
      <p className="legend">
        Where:
        <ul style={{ listStyleType: "none" }}>
          <li>
            <MathJaxContext>
              <MathJax>{"\\(R\\)"} &nbsp;- radius of the fixed circle</MathJax>
            </MathJaxContext>
          </li>
          <li>
            <MathJaxContext>
              <MathJax>
                {"\\(r\\)"} &nbsp;- radius of the hypocycle (rolling circle)
              </MathJax>
            </MathJaxContext>
          </li>
          <li>
            <MathJaxContext>
              <MathJax>{"\\(\\theta\\)"} &nbsp;- angle of rotation</MathJax>
            </MathJaxContext>
          </li>
        </ul>
      </p>
    </>
  );
};

export default HypocycloidInfo;
